### ISSUE TITLE
argument problems in test lab

### ISSUE THREAD

**Issue by ball00ns** [learn-co-curriculum/js-what-is-a-test-lab#8]
I can't pass the lesson because of this recurring argument, which I can't resolve:

```
what-is-a-test Height is less than 40:
     Error: The "actual" argument in expect(actual).toBeLessThan() must be a number
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBeLessThan (node_modules/expect/lib/Expectation.js:152:28)
      at Context.it (test/index-test.js:13:28)
```
I have not made any amendments to the original index-test file, what is going on :(

**Comment by maxwellbenton** [comment]
Hi @ball00ns,

Sorry to hear you were having difficulty with this lab. We've updated this lesson and included an additional error example to talk specifically about this message. In this case, the test expects `index.height` to be a number. If `index.height` is set to a string (`"40"` instead of `40`), this error will appear.

Thank you for taking the time to provide this feedback!
